# FUNDING.yml
# Support the research of Juan Moisés de la Serna Tuya
# ORCID: 0000-0002-8401-8018
# Universidad Internacional de La Rioja (UNIR)

# GitHub Sponsors (if enabled)
github: []

# Open Collective
open_collective: []

# Ko-fi
ko_fi: []

# Custom funding links
custom:
  - https://orcid.org/0000-0002-8401-8018
  - https://www.linkedin.com/in/juanmoisesdelaserna/
  - https://www.researchgate.net/profile/Juan_De_La_Serna_Tuya
